version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - ${ENV_FILE}